### ISSUE TITLE
8bit转16bit错误导致，杂音非常多

### ISSUE THREAD

**Issue by bylijian** [wanliyang1990/SoundTouch_OpenSL_Android#1]
sd_buffer[i] = (pcm_buffer[i * 2] | (pcm_buffer[i * 2 + 1] << 8)); 
这个代码有问题，pcm_buffer[i*2+1]的数据是byte的，对它进行左移八位，结果是全0！！！

**Comment by ywl5320** [comment]
这个转换是可以的哈，我再我的项目里面和课程里面都用到了的。还有这是处理ffmepg重采样后正确的PCM数据！！！

**Comment by bylijian** [comment]
可能是场景不一样，如果是这样,sd_buffer[i] = (pcm_buffer[i * 2] | (pcm_buffer[i * 2 + 1] << 8));
和sd_buffer[i] = pcm_buffer[i * 2]<<8;的意义应该是一样的。。。

**Comment by ywl5320** [comment]
对 这种要根据自己的使用场景灵活变化
